MiscBundle\Entity\BatchLock:
    type: entity
    repositoryClass: MiscBundle\Entity\Repository\BatchLockRepository
    table: batch_lock
    # indexes:
    id:
        batch_code:
            type: string
            length: 20
            nullable: false
            default: ''
    fields:
        locked:
            type: datetime
            nullable: false
        lock_key:
            type: string
            length: 255
            nullable: false
            default: ''
        info:
            type: string
            nullable: true
        last_notified:
            type: datetime
            nullable: true
        retry_count:
            type: integer
            nullable: false
            default: 0
        retry_count_max:
            type: integer
            nullable: false
            default: 0
        created:
            type: datetime
            nullable: false
        updated:
            type: datetime
            nullable: false

    lifecycleCallbacks:
        # 初回登録時 処理
        prePersist:
            - fillTimestamps
