MiscBundle\Entity\ChouchouClairProductLog:
    type: entity
    repositoryClass: MiscBundle\Entity\Repository\ChouchouClairProductLogRepository
    table: chouchou_clair_product_log
    # indexes:
    id:
        id:
            type: integer
            nullable: false
            id: true
            generator:
                strategy: AUTO
    fields:
        log_date:
            type: datetime
            nullable: false
        user_type:
            type: string
            length: 10
            nullable: false
            default: ''
        user:
            type: integer
            nullable: false
            default: 0
        operation:
            type: string
            length: 100
            nullable: false
            default: ''
        target:
            type: string
            length: 255
            nullable: false
            default: ''
        last_stock_modified:
            type: datetime
            nullable: true
        created:
            type: datetime
            nullable: true
        updated:
            type: datetime
            nullable: true

    lifecycleCallbacks:
        # 初回登録時 処理
        prePersist:
            - fillTimestamps
