MiscBundle\Entity\ForestMailtemplates:
  type: entity
  repositoryClass: MiscBundle\Entity\Repository\ForestMailtemplatesRepository
  table: forest_mailtemplates
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: false
      id: true
      generator:
        strategy: IDENTITY
  fields:
    choices1:
      type: string
      nullable: false
      length: 255
      options:
        fixed: false
        default: ''
    choices2:
      type: string
      nullable: false
      length: 255
      options:
        fixed: false
        default: ''
    choices3:
      type: string
      nullable: false
      length: 255
      options:
        fixed: false
        default: ''
    choices4:
      type: string
      nullable: false
      length: 255
      options:
        fixed: false
        default: ''
    choices5:
      type: string
      nullable: false
      length: 255
      options:
        fixed: false
        default: ''
    choices6:
      type: string
      nullable: false
      length: 255
      options:
        fixed: false
        default: ''
    choices7:
      type: string
      nullable: false
      length: 255
      options:
        fixed: false
        default: ''
    choices8:
      type: string
      nullable: false
      length: 255
      options:
        fixed: false
        default: ''
    choices9:
      type: string
      nullable: false
      length: 255
      options:
        fixed: false
        default: ''
    title:
      type: text
      nullable: false
      length: 65535
      options:
        fixed: false
        default: ''
    body:
      type: text
      nullable: false
      length: 65535
      options:
        fixed: false
        default: ''

    active:
      type: integer
      nullable: false
      options:
        default: -1

    type:
      type: string
      nullable: false
      length: 10
      options:
        default: 'a'

    created:
      type: datetime
      nullable: false
    updated:
      type: datetime
      nullable: false

  lifecycleCallbacks:
    # 初回登録時 処理
    prePersist:
      - fillTimestamps
