MiscBundle\Entity\MappedSuperClassTbMainproducts:
  type: mappedSuperclass

  id:
    daihyoSyohinCode:
      type: string
      nullable: false
      length: 30
      options:
        fixed: false
      id: true
      column: daihyo_syohin_code

  fields:

    sire_code:
      type: string
      nullable: true
      length: 10
      options:
        fixed: false
      column: sire_code

#    janCode:
#      type: string
#      nullable: true
#      length: 50
#      options:
#        fixed: false
#      column: jan_code
    syohin_kbn:
      type: string
      nullable: true
      length: 10
      options:
        fixed: false
        default: '10'
      column: syohin_kbn
    genka_tnk:
      type: integer
      nullable: true
      options:
        unsigned: true
      column: genka_tnk
    daihyo_syohin_name:
      type: string
      nullable: true
      length: 255
      options:
        fixed: false
      column: daihyo_syohin_name
#    在庫変動チェックフラグ:
#      type: boolean
#      nullable: true
#      options:
#        default: '0'
    price_unlinked_check:
      type: boolean
      nullable: true
      options:
        default: '0'
      column: 価格非連動チェック
#    バリエーション変更チェック:
#      type: boolean
#      nullable: true
#      options:
#        default: '0'
#    価格変更チェック:
#      type: boolean
#      nullable: true
#      options:
#        default: '0'
#    備考:
#      type: string
#      nullable: true
#      length: 255
#      options:
#        fixed: false
    order_comment:
      type: string
      nullable: true
      length: 255
      options:
        fixed: false
      column: 仕入備考

#    楽天削除:
#      type: boolean
#      nullable: true
#      options:
#        default: '0'
    registered_datetime:
      type: datetime
      nullable: true
      column: 登録日時
    sale_start_date:
      type: date
      nullable: true
      column: 販売開始日
    shippingdivision_id:
      type: integer
      nullable: false
      column: 送料設定
      options:
        default: '0'

#    入荷予定日:
#      type: date
#      nullable: true
#    入荷アラート日数:
#      type: integer
#      nullable: true
#      options:
#        unsigned: true
#        default: '0'
#    優先表示修正値:
#      type: integer
#      nullable: true
#      options:
#        unsigned: false
#        default: '0'
#    優先表示順位:
#      type: integer
#      nullable: true
#      options:
#        unsigned: false
#        default: '0'
    manual_guerrilla_sale:
      type: boolean
      nullable: true
      options:
        default: '0'
      column: 手動ゲリラSALE
#    入荷遅延日数:
#      type: integer
#      nullable: true
#      options:
#        unsigned: true
#        default: '0'
#    総在庫数:
#      type: integer
#      nullable: true
#      options:
#        unsigned: true
#        default: '0'
#    総在庫金額:
#      type: integer
#      nullable: true
#      options:
#        unsigned: true
#        default: '0'
    image_p1_caption:
      type: string
      nullable: true
      length: 50
      options:
        fixed: false
      column: 商品画像P1Cption
    image_p2_caption:
      type: string
      nullable: true
      length: 50
      options:
        fixed: false
      column: 商品画像P2Cption
    image_p3_caption:
      type: string
      nullable: true
      length: 50
      options:
        fixed: false
      column: 商品画像P3Cption
    image_p4_caption:
      type: string
      nullable: true
      length: 50
      options:
        fixed: false
      column: 商品画像P4Cption
    image_p5_caption:
      type: string
      nullable: true
      length: 50
      options:
        fixed: false
      column: 商品画像P5Cption
    image_p6_caption:
      type: string
      nullable: true
      length: 50
      options:
        fixed: false
      column: 商品画像P6Cption
    image_p7_caption:
      type: string
      nullable: true
      length: 50
      options:
        fixed: false
      column: 商品画像P7Cption
    image_p8_caption:
      type: string
      nullable: true
      length: 50
      options:
        fixed: false
      column: 商品画像P8Cption
    image_p9_caption:
      type: string
      nullable: true
      length: 50
      options:
        fixed: false
      column: 商品画像P9Cption
#    商品画像m1caption:
#      type: string
#      nullable: true
#      length: 50
#      options:
#        fixed: false
#      column: 商品画像M1Caption
#    商品画像m2caption:
#      type: string
#      nullable: true
#      length: 50
#      options:
#        fixed: false
#      column: 商品画像M2Caption
#    商品画像m3caption:
#      type: string
#      nullable: true
#      length: 50
#      options:
#        fixed: false
#      column: 商品画像M3Caption
    image_p1_address:
      type: string
      nullable: true
      length: 200
      options:
        fixed: false
      column: 商品画像P1Adress
    image_p2_address:
      type: string
      nullable: true
      length: 200
      options:
        fixed: false
      column: 商品画像P2Adress
    image_p3_address:
      type: string
      nullable: true
      length: 200
      options:
        fixed: false
      column: 商品画像P3Adress
    image_p4_address:
      type: string
      nullable: true
      length: 200
      options:
        fixed: false
      column: 商品画像P4Adress
    image_p5_address:
      type: string
      nullable: true
      length: 200
      options:
        fixed: false
      column: 商品画像P5Adress
    image_p6_address:
      type: string
      nullable: true
      length: 200
      options:
        fixed: false
      column: 商品画像P6Adress
    image_p7_address:
      type: string
      nullable: true
      length: 200
      options:
        fixed: false
      column: 商品画像P7Adress
    image_p8_address:
      type: string
      nullable: true
      length: 200
      options:
        fixed: false
      column: 商品画像P8Adress
    image_p9_address:
      type: string
      nullable: true
      length: 200
      options:
        fixed: false
      column: 商品画像P9Adress
#    商品画像m1adress:
#      type: string
#      nullable: true
#      length: 200
#      options:
#        fixed: false
#      column: 商品画像M1Adress
#    商品画像m2adress:
#      type: string
#      nullable: true
#      length: 200
#      options:
#        fixed: false
#      column: 商品画像M2Adress
#    商品画像m3adress:
#      type: string
#      nullable: true
#      length: 200
#      options:
#        fixed: false
#      column: 商品画像M3Adress

#    b固有必要補足説明:
#      type: text
#      nullable: true
#      length: 65535
#      options:
#        fixed: false
#      column: B固有必要補足説明
#    r固有必要補足説明:
#      type: text
#      nullable: true
#      length: 65535
#      options:
#        fixed: false
#      column: R固有必要補足説明
#    ne更新カラム:
#      type: string
#      nullable: true
#      length: 10
#      options:
#        fixed: false
#      column: NE更新カラム
#    gmoタイトル:
#      type: string
#      nullable: true
#      length: 255
#      options:
#        fixed: false
#      column: GMOタイトル

#    実勢価格:
#      type: integer
#      nullable: true
#      options:
#        unsigned: true

    col_type_name:
      type: string
      nullable: true
      length: 50
      options:
        fixed: false
      column: 横軸項目名
    row_type_name:
      type: string
      nullable: true
      length: 50
      options:
        fixed: false
      column: 縦軸項目名
    col_type:
      type: string
      nullable: true
      length: 10
      options:
        fixed: false
      column: col_type
    row_type:
      type: string
      nullable: true
      length: 10
      options:
        fixed: false
      column: row_type
    color_axis:
      type: string
      nullable: false
      length: 4
      options:
        fixed: false
        default: ''
      column: カラー軸

    ne_directory_id:
      type: string
      nullable: true
      length: 50
      options:
        fixed: false
      column: NEディレクトリID
    yahoo_directory_id:
      type: string
      nullable: true
      length: 20
      options:
        fixed: false
      column: YAHOOディレクトリID

#    標準出荷日数:
#      type: integer
#      nullable: true
#      options:
#        unsigned: true
#        default: '0'
#    stockreview:
#      type: boolean
#      nullable: true
#      options:
#        default: '0'
#    stockinfomation:
#      type: string
#      nullable: true
#      length: 255
#      options:
#        fixed: false
#    stockreviewinfomation:
#      type: string
#      nullable: true
#      length: 255
#      options:
#        fixed: false
#    productchoiceitemsCount:
#      type: integer
#      nullable: true
#      options:
#        unsigned: true
#        default: '0'
#      column: productchoiceitems_count
    image_p1_filename:
      type: string
      nullable: true
      length: 255
      options:
        fixed: false
      column: picnameP1
    image_p2_filename:
      type: string
      nullable: true
      length: 255
      options:
        fixed: false
      column: picnameP2
    image_p3_filename:
      type: string
      nullable: true
      length: 255
      options:
        fixed: false
      column: picnameP3
    image_p4_filename:
      type: string
      nullable: true
      length: 255
      options:
        fixed: false
      column: picnameP4
    image_p5_filename:
      type: string
      nullable: true
      length: 255
      options:
        fixed: false
      column: picnameP5
    image_p6_filename:
      type: string
      nullable: true
      length: 255
      options:
        fixed: false
      column: picnameP6
    image_p7_filename:
      type: string
      nullable: true
      length: 255
      options:
        fixed: false
      column: picnameP7
    image_p8_filename:
      type: string
      nullable: true
      length: 255
      options:
        fixed: false
      column: picnameP8
    image_p9_filename:
      type: string
      nullable: true
      length: 255
      options:
        fixed: false
      column: picnameP9
#    picname_m1:
#      type: string
#      nullable: true
#      length: 255
#      options:
#        fixed: false
#      column: picnameM1
#    picname_m2:
#      type: string
#      nullable: true
#      length: 255
#      options:
#        fixed: false
#      column: picnameM2
#    picname_m3:
#      type: string
#      nullable: true
#      length: 255
#      options:
#        fixed: false
#      column: picnameM3
    image_p1_directory:
      type: string
      nullable: true
      length: 255
      options:
        fixed: false
      column: picfolderP1
    image_p2_directory:
      type: string
      nullable: true
      length: 255
      options:
        fixed: false
      column: picfolderP2
    image_p3_directory:
      type: string
      nullable: true
      length: 255
      options:
        fixed: false
      column: picfolderP3
    image_p4_directory:
      type: string
      nullable: true
      length: 255
      options:
        fixed: false
      column: picfolderP4
    image_p5_directory:
      type: string
      nullable: true
      length: 255
      options:
        fixed: false
      column: picfolderP5
    image_p6_directory:
      type: string
      nullable: true
      length: 255
      options:
        fixed: false
      column: picfolderP6
    image_p7_directory:
      type: string
      nullable: true
      length: 255
      options:
        fixed: false
      column: picfolderP7
    image_p8_directory:
      type: string
      nullable: true
      length: 255
      options:
        fixed: false
      column: picfolderP8
    image_p9_directory:
      type: string
      nullable: true
      length: 255
      options:
        fixed: false
      column: picfolderP9
#    picfolder_m1:
#      type: string
#      nullable: true
#      length: 255
#      options:
#        fixed: false
#      column: picfolderM1
#    picfolder_m2:
#      type: string
#      nullable: true
#      length: 255
#      options:
#        fixed: false
#      column: picfolderM2
#    picfolder_m3:
#      type: string
#      nullable: true
#      length: 255
#      options:
#        fixed: false
#      column: picfolderM3
    person:
      type: string
      nullable: true
      length: 255
      options:
        fixed: false
#    checkPrice:
#      type: integer
#      nullable: true
#      options:
#        unsigned: true
#      column: check_price
    weight:
      type: integer
      nullable: false
      options:
        unsigned: true
        comment: 重量(g)
        default: '0'
    depth:
      type: integer
      nullable: false
      options:
        comment:  '縦（奥行き） mm'
        default: '0'
    width:
      type: integer
      nullable: false
      options:
        comment:  '横（横幅） mm'
        default: '0'
    height:
      type: integer
      nullable: false
      options:
        comment:  '高さ mm'
        default: '0'

#    additionalCost:
#      type: integer
#      nullable: false
#      options:
#        unsigned: true
#        comment: 仕入付加費用
#        default: '0'
#      column: additional_cost
#    picCheckDatetime:
#      type: datetime
#      nullable: true
#      options:
#        comment: 画像チェック日時
#      column: pic_check_datetime
#    picCheckDatetimeSort:
#      type: datetime
#      nullable: false
#      column: pic_check_datetime_sort
#    notfoundImageNoRakuten:
#      type: integer
#      nullable: false
#      options:
#        unsigned: false
#        default: '0'
#      column: notfound_image_no_rakuten
#    notfoundImageNoDena:
#      type: integer
#      nullable: false
#      options:
#        unsigned: false
#        default: '0'
#      column: notfound_image_no_dena

#    dummy:
#      type: integer
#      nullable: false
#      options:
#        unsigned: false
#        default: '0'


    # 説明文(PC)
    description:
      type: text
      nullable: true
      length: 65535
      options:
        fixed: false
      column: 商品コメントPC

    about_size:
      type: text
      nullable: true
      length: 65535
      options:
        fixed: false
      column: サイズについて

    about_color:
      type: text
      nullable: true
      length: 65535
      options:
        fixed: false
      column: カラーについて

    about_material:
      type: text
      nullable: true
      length: 65535
      options:
        fixed: false
      column: 素材について

    about_brand:
      type: text
      nullable: true
      length: 65535
      options:
        fixed: false
      column: ブランドについて

    usage_note:
      type: text
      nullable: true
      length: 65535
      options:
        fixed: false
      column: 使用上の注意

    # 補足説明(PC)
    supplemental_explanation:
      type: text
      nullable: true
      length: 65535
      options:
        fixed: false
      column: 補足説明PC

    # モバイル用説明文
    short_description:
      type: text
      nullable: true
      length: 65535
      options:
        fixed: false
      column: 一言ポイント

    # 補足説明(モバイル)
    short_supplemental_explanation:
      type: text
      nullable: true
      length: 65535
      options:
        fixed: false
      column: 必要補足説明

    # セット商品フラグ
    set_flg:
      type: integer
      nullable: false
      options:
        default: 0
      column: set_flg

    company_code:
      type: integer
      nullable: false
      options:
        unsigned: true
        comment: 会社ID

  lifecycleCallbacks: {  }
#
#  oneToOne:
#    cal:
#      targetEntity: TbMainproductsCal
#      mappedBy: product
#      fetch: EAGER
#
#  oneToMany:
#    choiceItems:
#      targetEntity: TbProductchoiceitems
#      mappedBy: product
#      # orderBy: displayOrder
#      orderBy:
#        displayOrder : ASC
#
#  manyToOne:
#    vendor:
#      targetEntity: TbVendormasterdata
#      # inversedBy: products
#      joinColumn:
#        name: sire_code
#        referencedColumnName: sire_code
#      fetch: EAGER
