MiscBundle\Entity\ProductImagesVariation:
    type: entity
    repositoryClass: MiscBundle\Entity\Repository\ProductImagesVariationRepository
    table: product_images_variation
    # indexes:
    id:
        daihyo_syohin_code:
            type: string
            length: 30
            nullable: false
            default: ''
        code:
            type: string
            length: 10
            nullable: false
            default: ''
        variation_code:
            type: string
            length: 30
            nullable: false
            default: ''
    fields:
        address:
            type: string
            length: 255
            nullable: false
            default: ''
        directory:
            type: string
            length: 20
            nullable: false
            default: ''
        filename:
            type: string
            length: 30
            nullable: false
            default: ''
        color_image_id:
            type: integer
            nullable: false
        created:
            type: datetime
            nullable: false
        updated:
            type: datetime
            nullable: false

    lifecycleCallbacks:
        # 初回登録時 処理
        prePersist:
            - fillTimestamps
