MiscBundle\Entity\ProductImages:
    type: entity
    repositoryClass: MiscBundle\Entity\Repository\ProductImagesRepository
    table: product_images
    # indexes:
    id:
        daihyo_syohin_code:
            type: string
            length: 30
            nullable: false
            default: ''
        code:
            type: string
            length: 10
            nullable: false
            default: ''
    fields:
        address:
            type: string
            length: 255
            nullable: false
            default: ''
        directory:
            type: string
            length: 20
            nullable: false
            default: ''
        filename:
            type: string
            length: 30
            nullable: false
            default: ''
        phash:
            type: string
            length: 16
            nullable: false
            default: ''
        md5hash:
            type: string
            length: 32
            nullable: false
            default: ''
        created:
            type: datetime
            nullable: false
        updated:
            type: datetime
            nullable: false

    lifecycleCallbacks:
        # 初回登録時 処理
        prePersist:
            - fillTimestamps
