MiscBundle\Entity\PurchasingAgent:
    type: entity
    repositoryClass: MiscBundle\Entity\Repository\BaseRepository
    table: purchasing_agent
    # indexes:
    id:
        id:
            type: integer
            nullable: false
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 100
            nullable: false
            options:
                default: ''
        login_name:
            type: string
            length: 10
            nullable: false
            options:
                default: ''
        display_order:
            type: integer
            nullable: false
            options:
                default: 0
        sire_code:
            type: string
            length: 10
            nullable: false
            options:
                default: ''
        created:
            type: datetime
            nullable: false
        updated:
            type: datetime
            nullable: false

    lifecycleCallbacks:
        # 初回登録時 処理
        prePersist:
            - fillTimestamps
