MiscBundle\Entity\SymfonyUserYahooAgent:
    type: entity
    repositoryClass: MiscBundle\Entity\Repository\SymfonyUserYahooAgentRepository
    table: symfony_user_yahoo_agent
    uniqueConstraints:
        unique_username:
            columns:
                - username
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            nullable: false
            length: 24
            options:
                fixed: false
        password:
            type: string
            nullable: false
            length: 64
            options:
                fixed: false
        client_name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        email:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                default: ''
        is_active:
            type: integer
            nullable: false
            options:
                default: -1
        roles:
            type: string
            nullable: true

        shop_code:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
        app_id:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                default: ''
        app_secret:
            type: string
            nullable: false
            length: 40
            options:
                fixed: false
                default: ''
        ftp_user:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
                default: ''
        ftp_password:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                default: ''

        created_at:
            type: datetime
            nullable: false
        updated_at:
            type: datetime
            nullable: false

    # see http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/events.html#lifecycle-events
    lifecycleCallbacks:
        # 初回登録時 処理
        prePersist:
            - fillTimestamps
        # postPersist: [ doStuffOnPostPersist ]
        # 更新時 処理
        preUpdate:
            - preUpdate

