MiscBundle\Entity\SymfonyUserClient:
    type: entity
    repositoryClass: MiscBundle\Entity\Repository\SymfonyUserClientRepository
    table: symfony_user_client
    uniqueConstraints:
        unique_username:
            columns:
                - agent_id
                - username
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            nullable: false
            length: 24
            options:
                fixed: false
        password:
            type: string
            nullable: false
            length: 64
            options:
                fixed: false
        agent_id:
            type: integer
            nullable: false
            options:
                default: 0
        email:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                default: ''
        is_active:
            type: integer
            nullable: false
            options:
                default: -1
        roles:
            type: string
            nullable: true
        last_login_datetime:
          type: datetime
          nullable: true
          options:
            default: null
        created_at:
            type: datetime
            nullable: false
        updated_at:
            type: datetime
            nullable: false

    # see http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/events.html#lifecycle-events
    lifecycleCallbacks:
        # 初回登録時 処理
        prePersist:
            - fillTimestamps
        # postPersist: [ doStuffOnPostPersist ]
        # 更新時 処理
        preUpdate:
            - preUpdate

