MiscBundle\Entity\Tb1688Product:
  type: entity
  repositoryClass: MiscBundle\Entity\Repository\Tb1688ProductRepository
  table: tb_1688_product
  id:
    offer_id:
      type: integer
      nullable: false
      id: true
      column: offer_id
  fields:
    details_url:
      type: string
      nullable: false
      length: 255
      options:
        default: ''

    member_id:
      type: string
      nullable: false
      length: 30
      options:
        default: ''

    type:
      type: string
      nullable: false
      length: 20
      options:
        default: ''

    offer_status:
      type: string
      nullable: false
      length: 30
      options:
        default: ''

    subject:
      type: string
      nullable: false
      length: 255
      options:
        default: ''

    quality_level:
      type: integer
      nullable: false
      options:
        default: 0

    trade_type:
      type: integer
      nullable: false
      options:
        default: 0

    post_categry_id:
      type: integer
      nullable: false
      options:
        default: 0

    unit:
      type: string
      nullable: false
      length: 30
      options:
        default: ''

    price_unit:
      type: string
      nullable: false
      length: 20
      options:
        default: ''

    amount:
      type: integer
      nullable: false
      options:
        default: 0

    amount_on_sale:
      type: integer
      nullable: false
      options:
        default: 0

    saled_count:
      type: integer
      nullable: false
      options:
        default: 0

    product_unit_weight:
      type: decimal
      nullable: false
      precision: 10
      scale: 4
      options:
        default: 0

    freight_type:
      type: string
      nullable: false
      length: 10
      options:
        default: ''

    term_offer_process:
      type: integer
      nullable: false
      options:
        default: 0

    is_private:
      type: integer
      nullable: false
      options:
        default: 0

    is_private_offer:
      type: integer
      nullable: false
      options:
        default: 0

    is_price_auth_offer:
      type: integer
      nullable: false
      options:
        default: 0

    is_pic_auth_offer:
      type: integer
      nullable: false
      options:
        default: 0

    is_offer_support_online_trade:
      type: integer
      nullable: false
      options:
        default: 0

    is_sku_offer:
      type: integer
      nullable: false
      options:
        default: 0

    is_sku_trade_supported:
      type: integer
      nullable: false
      options:
        default: 0

    is_support_mix:
      type: integer
      nullable: false
      options:
        default: 0

    gmt_create:
      type: datetime
      nullable: true

    gmt_modified:
      type: datetime
      nullable: true

    gmt_last_repost:
      type: datetime
      nullable: true

    gmt_approved:
      type: datetime
      nullable: true

    gmt_expire:
      type: datetime
      nullable: true

    sku_num:
      type: integer
      nullable: false
      options:
        default: 0

    sku_active_num:
      type: integer
      nullable: false
      options:
        default: 0

    last_checked:
      type: datetime
      nullable: true

    created:
      type: datetime
      nullable: false

    updated:
      type: datetime
      nullable: false

  lifecycleCallbacks:
    # 初回登録時 処理
    prePersist:
        - fillTimestamps
