MiscBundle\Entity\Tb1688Company:
  type: entity
  repositoryClass: MiscBundle\Entity\Repository\Tb1688CompanyRepository
  table: tb_1688_company
  id:
    member_id:
      type: string
      nullable: false
      length: 30
      id: true
  fields:
    company_name:
      type: string
      nullable: false
      length: 255
      options:
        default:''

    url:
      type: string
      nullable: false
      length: 255
      options:
        default:''

    company_category_info:
      type: string
      nullable: true

    company_name_en:
      type: string
      nullable: false
      length: 255
      options:
        default:''

    production_service:
      type: string
      nullable: false
      length: 255
      options:
        default:''

    legal_status:
      type: string
      nullable: false
      length: 100
      options:
        default:''

    biz_place:
      type: string
      nullable: false
      length: 100
      options:
        default:''

    biz_model:
      type: string
      nullable: false
      length: 100
      options:
        default:''

    profile:
      type: string
      nullable: true

    sire_code:
      type: string
      nullable: false
      length: 10
      options:
        default:''

    registration_stop:
      type: integer
      nullable: false
      options:
        default:0

    check_stop:
      type: integer
      nullable: false
      options:
        default:0

    created:
      type: datetime
      nullable: false

    updated:
      type: datetime
      nullable: false

  lifecycleCallbacks:
    # 初回登録時 処理
    prePersist:
        - fillTimestamps
