MiscBundle\Entity\TbBiddersinfomation:
  type: entity
  table: tb_biddersinfomation
  fields:
    title:
      type: string
      nullable: true
      length: 255
      fixed: false
      column: bidders_title
    searchKeyword1:
      type: string
      nullable: true
      length: 255
      fixed: false
      column: search_keyword1
    searchKeyword2:
      type: string
      nullable: true
      length: 255
      fixed: false
      default: 春夏秋冬サマー
      column: search_keyword2
    searchKeyword3:
      type: string
      nullable: true
      length: 255
      fixed: false
      default: 激安バーゲンセール
      column: search_keyword3
  lifecycleCallbacks: {}
