MiscBundle\Entity\TbDeliveryPickingBlockDetail:
    type: entity
    # repositoryClass: MiscBundle\Entity\Repository\TbDeliveryPickingBlockRepository
    table: tb_delivery_picking_block_detail

    id:
        warehouse_id:
            type: integer
            nullable: false
        block_code:
            type: string
            length: 4
            nullable: false
        pattern:
            type: string
            length: 30
            nullable: false
    fields:

        created:
            type: datetime
            nullable: false
        updated:
            type: datetime
            nullable: false

    lifecycleCallbacks:
        # 初回登録時 処理
        prePersist:
            - fillTimestamps
