MiscBundle\Entity\TbDeliveryPickingBlock:
    type: entity
    repositoryClass: MiscBundle\Entity\Repository\TbDeliveryPickingBlockRepository
    table: tb_delivery_picking_block

    id:
        warehouse_id:
            type: integer
            nullable: false
        block_code:
            type: string
            length: 4
            nullable: false

    fields:
        display_order:
            type: integer
            nullable: false
            default: 0

        created:
            type: datetime
            nullable: false
        updated:
            type: datetime
            nullable: false

    lifecycleCallbacks:
        # 初回登録時 処理
        prePersist:
            - fillTimestamps
