MiscBundle\Entity\TbDiscountSetting:
    type: entity
    repositoryClass: MiscBundle\Entity\Repository\TbDiscountSettingRepository
    table: tb_discount_setting
    # indexes:
    id:
        id:
            type: integer
            nullable: false
    fields:
        discount_excluded_days:
            type: integer
            nullable: false
            default: 0
        sales_term_days:
            type: integer
            nullable: false
            default: 0
        sales_sampling_days:
            type: integer
            nullable: false
            default: 0
        sell_out_days:
            type: integer
            nullable: false
            default: 0
        allowed_sell_out_over_days:
            type: integer
            nullable: false
            default: 0
        max_discount_rate:
            type: integer
            nullable: false
            default: 0
        limitWithinDays1:
            type: integer
            nullable: true
            comment: "値下げ幅制限期間1\n最終仕入れ日からの日数"
            column: limit_within_days1
        limitRateForCost1:
            type: integer
            nullable: true
            unsigned: false
            comment: "値下げ幅制限率1\n売価原価に対する率"
            column: limit_rate_for_cost1
        limitWithinDays2:
            type: integer
            nullable: true
            unsigned: false
            comment: "値下げ幅制限期間2\n最終仕入れ日からの日数"
            column: limit_within_days2
        limitRateForCost2:
            type: integer
            nullable: true
            unsigned: false
            comment: "値下げ幅制限率2\n売価原価に対する率"
            column: limit_rate_for_cost2
        limitWithinDays3:
            type: integer
            nullable: true
            unsigned: false
            comment: "値下げ幅制限期間3\n最終仕入れ日からの日数"
            column: limit_within_days3
        limitRateForCost3:
            type: integer
            nullable: true
            unsigned: false
            comment: "値下げ幅制限率3\n売価原価に対する率"
            column: limit_rate_for_cost3
        created:
            type: datetime
            nullable: false
        updated:
            type: datetime
            nullable: false

    lifecycleCallbacks:
        # 初回登録時 処理
        prePersist:
            - fillTimestamps
