MiscBundle\Entity\TbMixedProduct:
  type: entity
  table: tb_mixed_product
  repositoryClass: MiscBundle\Entity\Repository\TbMixedProductRepository

  id:
    mall_code:
      type: string
      nullable: false
      length: 20
      options:
        fixed: false
      id: true

    daihyo_syohin_code:
      type: string
      nullable: false
      length: 30
      options:
        fixed: false
      id: true

  fields:
    parent:
      type: string
      nullable: false
      length: 30
      options:
        fixed: false
    display_order:
      type: integer
      nullable: false
      options:
          default: 0
    created:
      type: datetime
      nullable: false
    updated:
      type: datetime
      nullable: false

  lifecycleCallbacks:
    # 初回登録時 処理
    prePersist:
      - fillTimestamps
