MiscBundle\Entity\TbNeMallProductSkuRegistration:
  type: entity
  repositoryClass: MiscBundle\Entity\Repository\TbNeMallProductSkuRegistrationRepository
  table: tb_ne_mall_product_sku_registration
  uniqueConstraints:
    key_ne_syohin_syohin_code:
      columns:
        - ne_syohin_syohin_code
        - ne_mall_id
  indexes:
    index_ne_syohin_syohin_code_ne_mall_id_registration_flg:
      columns:
        - ne_syohin_syohin_code
        - ne_mall_id
        - registration_flg
  id:
    id:
      type: integer
      nullable: false
      unsigned: false
      comment: ID
      id: true
      generator:
        strategy: IDENTITY
  fields:
    neSyohinSyohinCode:
      type: string
      nullable: false
      length: 255
      fixed: false
      comment: SKUコード
      column: ne_syohin_syohin_code
    neMallId:
      type: integer
      nullable: false
      unsigned: false
      comment: "店舗コード\nNE側店舗コード。tb_shopping_mall.id ではない"
      column: ne_mall_id
    registrationFlg:
      type: boolean
      nullable: false
      comment: "登録フラグ\n0:NEに未登録、1:NEに登録済み"
      default: "0"
      column: registration_flg
  lifecycleCallbacks: {}
