MiscBundle\Entity\TbProductLocationLogComment:
  type: entity
  repositoryClass: MiscBundle\Entity\Repository\BaseRepository
  table: tb_product_location_log_comment

  id:
    id:
      type: integer
      nullable: false
      generator:
          strategy: IDENTITY

  fields:
    account:
      type: string
      length: 30
      nullable: false
    operation:
      type: string
      length: 50
      nullable: false
    action_key:
      type: string
      length: 24
      nullable: false
    comment:
      type: string
      nullable: true

    created:
      type: datetime
      nullable: true

  lifecycleCallbacks:
    # 初回登録時 処理
    prePersist:
      - fillTimestamps
