MiscBundle\Entity\TbProductCostRateListSetting:
  type: entity
  repositoryClass: MiscBundle\Entity\Repository\TbProductCostRateListSettingRepository
  table: tb_product_cost_rate_list_setting
  id:
    id:
      type: integer
      nullable: false

  fields:
    threshold_voucher_num:
      type: decimal
      nullable: false
      default: 0
    threshold_voucher_term:
      type: integer
      nullable: false
      default: 0
    sampling_days:
      type: integer
      nullable: false
      default: 0
    move_threshold_rate:
      type: integer
      nullable: false
      default: 0
    shake_border:
      type: integer
      nullable: false
      default: 0
    change_amount_up:
      type: integer
      nullable: false
      default: 0
    change_amount_down:
      type: integer
      nullable: false
      default: 0
    change_amount_additional:
      type: integer
      nullable: false
      default: 0
    created:
      type: datetime
      nullable: false
    updated:
      type: datetime
      nullable: false

  lifecycleCallbacks:
    # 初回登録時 処理
    prePersist:
      - fillTimestamps
