MiscBundle\Entity\TbProductCostRateList:
  type: entity
  repositoryClass: MiscBundle\Entity\Repository\TbProductCostRateListRepository
  table: tb_product_cost_rate_list
  id:
    daihyo_syohin_code:
      type: string
      nullable: false
      length: 30
      options:
        fixed: false
      id: true
      column: daihyo_syohin_code
      generator:
        strategy: IDENTITY

  fields:
    cost_rate_after:
      type: decimal
      nullable: false
      options:
        default: 0
      column: cost_rate_after

    log_cost_rate_average_a:
      type: decimal
      nullable: false
      options:
        default: 0
      column: log_cost_rate_average_a

    log_profit_a:
      type: integer
      nullable: false
      options:
        default: 0
      column: log_profit_a

    log_voucher_num_a:
      type: integer
      nullable: false
      options:
        default: 0
      column: log_voucher_num_a

    log_cost_rate_average_b:
      type: decimal
      nullable: false
      options:
        default: 0
      column: log_cost_rate_average_b

    log_profit_b:
      type: integer
      nullable: false
      options:
        default: 0
      column: log_profit_b

    log_voucher_num_b:
      type: integer
      nullable: false
      options:
        default: 0
      column: log_voucher_num_b

    accumulated_cost_rate_change:
      type: integer
      nullable: false
      options:
        default: 0
      column: accumulated_cost_rate_change

    threshold_term_voucher_num_average:
      type: string
      nullable: false
      options:
        default: 0
      column: threshold_term_voucher_num_average

    shaken:
      type: integer
      nullable: false
      options:
        default: 0
      column: shaken

    created:
      type: datetime
      nullable: false
    updated:
      type: datetime
      nullable: false

  lifecycleCallbacks:
    # 初回登録時 処理
    prePersist:
      - fillTimestamps

  # joins
  oneToOne:
    product:
      targetEntity: TbMainproducts
      # inversedBy: cal
      joinColumn:
        name: daihyo_syohin_code
        referencedColumnName: daihyo_syohin_code
      fetch: EAGER

    cal:
      targetEntity: TbMainproductsCal
      # inversedBy: cal
      joinColumn:
        name: daihyo_syohin_code
        referencedColumnName: daihyo_syohin_code
      fetch: EAGER
