MiscBundle\Entity\TbPrefecture:
    type: entity
    repositoryClass: MiscBundle\Entity\Repository\TbPrefectureRepository
    table: tb_prefecture
    id:
        prefectureCd:
            type: string
            nullable: false
            length: 2
            fixed: true
            comment: 都道府県コード
            id: true
            column: prefecture_cd
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 4
            fixed: false
            comment: 都道府県名
            default: ''
    lifecycleCallbacks: {  }
