MiscBundle\Entity\TbProductCode:
  type: entity
  repositoryClass: MiscBundle\Entity\Repository\TbProductCodeRepository
  table: tb_product_code

  id:
    id:
      type: integer
      nullable: false
      options:
      id: true

  fields:
    ne_syohin_syohin_code:
      type: string
      nullable: false
      length: 50
      options:
        fixed: false
    barcode:
      type: string
      nullable: false
      length: 13
      options:
        fixed: false

  lifecycleCallbacks: {}
