MiscBundle\Entity\TbProductSalesTask:
    type: entity
    repositoryClass: MiscBundle\Entity\Repository\TbProductSalesTaskRepository
    table: tb_product_sales_task
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: 商品売上タスクID
            id: true
            generator:
                strategy: IDENTITY
    fields:
        taskName:
            type: string
            nullable: false
            length: 24
            fixed: false
            comment: タスク名
            column: task_name
        multiProductRegisterFlg:
            type: boolean
            nullable: false
            comment: "複数対象商品登録フラグ\n0:単体, 1:複数対象商品"
            default: '1'
            column: multi_product_register_flg
        deleteFlg:
            type: boolean
            nullable: false
            comment: "削除フラグ\n0:未削除, 1:削除済み"
            default: '0'
            column: delete_flg
    lifecycleCallbacks: {  }