MiscBundle\Entity\TbRakutenTagProductchoiceitems:
    type: entity
    repositoryClass: MiscBundle\Entity\Repository\BaseRepository
    table: tb_rakuten_tag_productchoiceitems
    id:
        ne_syohin_syohin_code:
            type: string
            length: 30
            nullable: false
            id: true
            column: ne_syohin_syohin_code
        directory_id:
            type: string
            length: 15
            nullable: false
            id: true
            column: ディレクトリID
        tag_id:
            type: string
            length: 15
            nullable: false
            id: true
            column: タグID

    fields:
        daihyo_syohin_code:
            type: string
            length: 30
            nullable: false
            column: daihyo_syohin_code
        created:
            type: datetime
            nullable: false
        updated:
            type: datetime
            nullable: false

    lifecycleCallbacks:
        # 初回登録時 処理
        prePersist:
            - fillTimestamps
