MiscBundle\Entity\TbRealShopInformation:
    type: entity
    repositoryClass: MiscBundle\Entity\Repository\TbRealShopInformationRepository
    table: tb_real_shop_information
    id:
        daihyo_syohin_code:
            type: string
            nullable: false
            length: 30
            id: true
            column: daihyo_syohin_code

    fields:
        baika_tanka:
            type: integer
            nullable: false
            options:
                default: 0

        original_price:
            type: integer
            nullable: false
            options:
                default: 0

        label_type:
            type: string
            length: 10
            nullable: false
            options:
                default: 'tag'

        created:
            type: datetime
            nullable: false

        updated:
            type: datetime
            nullable: false

    lifecycleCallbacks:
        # 初回登録時 処理
        prePersist:
            - fillTimestamps
