MiscBundle\Entity\TbRfidReadings:
  type: entity
  table: tb_rfid_readings
  repositoryClass: MiscBundle\Entity\Repository\TbRfidReadingsRepository
  indexes:
    reading_id:
      columns:
        - reading_id
  id:
    id:
      type: integer
      nullable: false
      unsigned: false
      comment: ID
      id: true
      generator:
        strategy: IDENTITY
  fields:
    readingId:
      type: integer
      nullable: false
      unsigned: false
      comment: 読取ID
      column: reading_id
    boxTag:
      type: string
      nullable: false
      length: 40
      fixed: false
      comment: 箱タグ
      default: ''
      column: box_tag
    productTag:
      type: string
      nullable: false
      length: 40
      fixed: false
      comment: 商品タグ
      column: product_tag
    createdAt:
      type: datetime
      nullable: false
      comment: 登録日時
      default: CURRENT_TIMESTAMP
      column: created_at
    updatedAt:
      type: datetime
      nullable: false
      comment: 更新日時
      default: CURRENT_TIMESTAMP
      column: updated_at
  lifecycleCallbacks:
    prePersist:
      - fillTimestamps
