MiscBundle\Entity\TbSalesDetailVoucherSireOrderYmTrasition12:
    type: entity
    table: tb_sales_detail_voucher_sire_order_ym_trasition12
    id:
        sireCode:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
            id: true
            column: sire_code
            generator:
                strategy: IDENTITY
#    fields:
#        出品数:
#            type: integer
#            nullable: false
#            options:
#                unsigned: false
#                default: '0'
#        受注年月01:
#            type: string
#            nullable: false
#            length: 6
#            options:
#                fixed: false
#                default: ''
#        伝票数01:
#            type: integer
#            nullable: false
#            options:
#                unsigned: false
#                default: '0'
#        伝票金額01:
#            type: float
#            nullable: false
#            precision: 10
#            scale: 0
#            options:
#                default: '0'
#        伝票粗利額01:
#            type: float
#            nullable: false
#            precision: 10
#            scale: 0
#            options:
#                default: '0'
#        伝票粗利率01:
#            type: float
#            nullable: false
#            precision: 10
#            scale: 0
#            options:
#                default: '0'
#        1伝票粗利額01:
#            type: float
#            nullable: false
#            precision: 10
#            scale: 0
#            options:
#                default: '0'
#        1出品粗利額01:
#            type: float
#            nullable: false
#            precision: 10
#            scale: 0
#            options:
#                default: '0'
#        受注年月02:
#            type: string
#            nullable: false
#            length: 6
#            options:
#                fixed: false
#                default: ''
#        伝票数02:
#            type: integer
#            nullable: false
#            options:
#                unsigned: false
#                default: '0'
#        伝票金額02:
#            type: float
#            nullable: false
#            precision: 10
#            scale: 0
#            options:
#                default: '0'
#        伝票粗利額02:
#            type: float
#            nullable: false
#            precision: 10
#            scale: 0
#            options:
#                default: '0'
#        伝票粗利率02:
#            type: float
#            nullable: false
#            precision: 10
#            scale: 0
#            options:
#                default: '0'
#        1伝票粗利額02:
#            type: float
#            nullable: false
#            precision: 10
#            scale: 0
#            options:
#                default: '0'
#        1出品粗利額02:
#            type: float
#            nullable: false
#            precision: 10
#            scale: 0
#            options:
#                default: '0'
#        受注年月03:
#            type: string
#            nullable: false
#            length: 6
#            options:
#                fixed: false
#                default: ''
#        伝票数03:
#            type: integer
#            nullable: false
#            options:
#                unsigned: false
#                default: '0'
#        伝票金額03:
#            type: float
#            nullable: false
#            precision: 10
#            scale: 0
#            options:
#                default: '0'
#        伝票粗利額03:
#            type: float
#            nullable: false
#            precision: 10
#            scale: 0
#            options:
#                default: '0'
#        伝票粗利率03:
#            type: float
#            nullable: false
#            precision: 10
#            scale: 0
#            options:
#                default: '0'
#        1伝票粗利額03:
#            type: float
#            nullable: false
#            precision: 10
#            scale: 0
#            options:
#                default: '0'
#        1出品粗利額03:
#            type: float
#            nullable: false
#            precision: 10
#            scale: 0
#            options:
#                default: '0'
#        受注年月04:
#            type: string
#            nullable: false
#            length: 6
#            options:
#                fixed: false
#                default: ''
#        伝票数04:
#            type: integer
#            nullable: false
#            options:
#                unsigned: false
#                default: '0'
#        伝票金額04:
#            type: float
#            nullable: false
#            precision: 10
#            scale: 0
#            options:
#                default: '0'
#        伝票粗利額04:
#            type: float
#            nullable: false
#            precision: 10
#            scale: 0
#            options:
#                default: '0'
#        伝票粗利率04:
#            type: float
#            nullable: false
#            precision: 10
#            scale: 0
#            options:
#                default: '0'
#        1伝票粗利額04:
#            type: float
#            nullable: false
#            precision: 10
#            scale: 0
#            options:
#                default: '0'
#        1出品粗利額04:
#            type: float
#            nullable: false
#            precision: 10
#            scale: 0
#            options:
#                default: '0'
#        受注年月05:
#            type: string
#            nullable: false
#            length: 6
#            options:
#                fixed: false
#                default: ''
#        伝票数05:
#            type: integer
#            nullable: false
#            options:
#                unsigned: false
#                default: '0'
#        伝票金額05:
#            type: float
#            nullable: false
#            precision: 10
#            scale: 0
#            options:
#                default: '0'
#        伝票粗利額05:
#            type: float
#            nullable: false
#            precision: 10
#            scale: 0
#            options:
#                default: '0'
#        伝票粗利率05:
#            type: float
#            nullable: false
#            precision: 10
#            scale: 0
#            options:
#                default: '0'
#        1伝票粗利額05:
#            type: float
#            nullable: false
#            precision: 10
#            scale: 0
#            options:
#                default: '0'
#        1出品粗利額05:
#            type: float
#            nullable: false
#            precision: 10
#            scale: 0
#            options:
#                default: '0'
#        受注年月06:
#            type: string
#            nullable: false
#            length: 6
#            options:
#                fixed: false
#                default: ''
#        伝票数06:
#            type: integer
#            nullable: false
#            options:
#                unsigned: false
#                default: '0'
#        伝票金額06:
#            type: float
#            nullable: false
#            precision: 10
#            scale: 0
#            options:
#                default: '0'
#        伝票粗利額06:
#            type: float
#            nullable: false
#            precision: 10
#            scale: 0
#            options:
#                default: '0'
#        伝票粗利率06:
#            type: float
#            nullable: false
#            precision: 10
#            scale: 0
#            options:
#                default: '0'
#        1伝票粗利額06:
#            type: float
#            nullable: false
#            precision: 10
#            scale: 0
#            options:
#                default: '0'
#        1出品粗利額06:
#            type: float
#            nullable: false
#            precision: 10
#            scale: 0
#            options:
#                default: '0'
#        受注年月07:
#            type: string
#            nullable: false
#            length: 6
#            options:
#                fixed: false
#                default: ''
#        伝票数07:
#            type: integer
#            nullable: false
#            options:
#                unsigned: false
#                default: '0'
#        伝票金額07:
#            type: float
#            nullable: false
#            precision: 10
#            scale: 0
#            options:
#                default: '0'
#        伝票粗利額07:
#            type: float
#            nullable: false
#            precision: 10
#            scale: 0
#            options:
#                default: '0'
#        伝票粗利率07:
#            type: float
#            nullable: false
#            precision: 10
#            scale: 0
#            options:
#                default: '0'
#        1伝票粗利額07:
#            type: float
#            nullable: false
#            precision: 10
#            scale: 0
#            options:
#                default: '0'
#        1出品粗利額07:
#            type: float
#            nullable: false
#            precision: 10
#            scale: 0
#            options:
#                default: '0'
#        受注年月08:
#            type: string
#            nullable: false
#            length: 6
#            options:
#                fixed: false
#                default: ''
#        伝票数08:
#            type: integer
#            nullable: false
#            options:
#                unsigned: false
#                default: '0'
#        伝票金額08:
#            type: float
#            nullable: false
#            precision: 10
#            scale: 0
#            options:
#                default: '0'
#        伝票粗利額08:
#            type: float
#            nullable: false
#            precision: 10
#            scale: 0
#            options:
#                default: '0'
#        伝票粗利率08:
#            type: float
#            nullable: false
#            precision: 10
#            scale: 0
#            options:
#                default: '0'
#        1伝票粗利額08:
#            type: float
#            nullable: false
#            precision: 10
#            scale: 0
#            options:
#                default: '0'
#        1出品粗利額08:
#            type: float
#            nullable: false
#            precision: 10
#            scale: 0
#            options:
#                default: '0'
#        受注年月09:
#            type: string
#            nullable: false
#            length: 6
#            options:
#                fixed: false
#                default: ''
#        伝票数09:
#            type: integer
#            nullable: false
#            options:
#                unsigned: false
#                default: '0'
#        伝票金額09:
#            type: float
#            nullable: false
#            precision: 10
#            scale: 0
#            options:
#                default: '0'
#        伝票粗利額09:
#            type: float
#            nullable: false
#            precision: 10
#            scale: 0
#            options:
#                default: '0'
#        伝票粗利率09:
#            type: float
#            nullable: false
#            precision: 10
#            scale: 0
#            options:
#                default: '0'
#        1伝票粗利額09:
#            type: float
#            nullable: false
#            precision: 10
#            scale: 0
#            options:
#                default: '0'
#        1出品粗利額09:
#            type: float
#            nullable: false
#            precision: 10
#            scale: 0
#            options:
#                default: '0'
#        受注年月10:
#            type: string
#            nullable: false
#            length: 6
#            options:
#                fixed: false
#                default: ''
#        伝票数10:
#            type: integer
#            nullable: false
#            options:
#                unsigned: false
#                default: '0'
#        伝票金額10:
#            type: float
#            nullable: false
#            precision: 10
#            scale: 0
#            options:
#                default: '0'
#        伝票粗利額10:
#            type: float
#            nullable: false
#            precision: 10
#            scale: 0
#            options:
#                default: '0'
#        伝票粗利率10:
#            type: float
#            nullable: false
#            precision: 10
#            scale: 0
#            options:
#                default: '0'
#        1伝票粗利額10:
#            type: float
#            nullable: false
#            precision: 10
#            scale: 0
#            options:
#                default: '0'
#        1出品粗利額10:
#            type: float
#            nullable: false
#            precision: 10
#            scale: 0
#            options:
#                default: '0'
#        受注年月11:
#            type: string
#            nullable: false
#            length: 6
#            options:
#                fixed: false
#                default: ''
#        伝票数11:
#            type: integer
#            nullable: false
#            options:
#                unsigned: false
#                default: '0'
#        伝票金額11:
#            type: float
#            nullable: false
#            precision: 10
#            scale: 0
#            options:
#                default: '0'
#        伝票粗利額11:
#            type: float
#            nullable: false
#            precision: 10
#            scale: 0
#            options:
#                default: '0'
#        伝票粗利率11:
#            type: float
#            nullable: false
#            precision: 10
#            scale: 0
#            options:
#                default: '0'
#        1伝票粗利額11:
#            type: float
#            nullable: false
#            precision: 10
#            scale: 0
#            options:
#                default: '0'
#        1出品粗利額11:
#            type: float
#            nullable: false
#            precision: 10
#            scale: 0
#            options:
#                default: '0'
#        受注年月12:
#            type: string
#            nullable: false
#            length: 6
#            options:
#                fixed: false
#                default: ''
#        伝票数12:
#            type: integer
#            nullable: false
#            options:
#                unsigned: false
#                default: '0'
#        伝票金額12:
#            type: float
#            nullable: false
#            precision: 10
#            scale: 0
#            options:
#                default: '0'
#        伝票粗利額12:
#            type: float
#            nullable: false
#            precision: 10
#            scale: 0
#            options:
#                default: '0'
#        伝票粗利率12:
#            type: float
#            nullable: false
#            precision: 10
#            scale: 0
#            options:
#                default: '0'
#        1伝票粗利額12:
#            type: float
#            nullable: false
#            precision: 10
#            scale: 0
#            options:
#                default: '0'
#        1出品粗利額12:
#            type: float
#            nullable: false
#            precision: 10
#            scale: 0
#            options:
#                default: '0'
    lifecycleCallbacks: {  }
