MiscBundle\Entity\TbSalesDetailVoucherSireOrderYm:
    type: entity
    table: tb_sales_detail_voucher_sire_order_ym
    id:
        sireCode:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
            id: true
            column: sire_code
#        受注年月:
#            type: string
#            nullable: false
#            length: 6
#            options:
#                fixed: false
#                default: ''
#            id: true
#    fields:
#        受注年:
#            type: integer
#            nullable: true
#            options:
#                unsigned: false
#        受注月:
#            type: integer
#            nullable: true
#            options:
#                unsigned: false
#        伝票数:
#            type: integer
#            nullable: false
#            options:
#                unsigned: false
#                default: '0'
#        伝票金額:
#            type: float
#            nullable: false
#            precision: 10
#            scale: 0
#            options:
#                default: '0'
#        伝票粗利額:
#            type: float
#            nullable: false
#            precision: 10
#            scale: 0
#            options:
#                default: '0'
#        伝票粗利率:
#            type: float
#            nullable: false
#            precision: 10
#            scale: 0
#            options:
#                default: '0'
    lifecycleCallbacks: {  }
