MiscBundle\Entity\TbSalesVoucherDeliveryInfo:
  type: entity
  # repositoryClass: MiscBundle\Entity\Repository\TbSalesVoucherDeliveryInfoRepository
  table: tb_sales_voucher_delivery_info
  id:
    voucher_number:
      type: string
      length: 20
      nullable: false
      default: ''
  fields:
    receive_order_hope_delivery_time_slot_id:
      type: string
      length: 100
      nullable: false
      default: ''
    receive_order_temperature_id:
      type: string
      length: 100
      nullable: false
      default: ''
    receive_order_business_office_stop_id:
      type: string
      length: 100
      nullable: false
      default: ''
    receive_order_business_office_name:
      type: string
      length: 255
      nullable: false
      default: ''

    created:
      type: datetime
      nullable: false
    updated:
      type: datetime
      nullable: false

  lifecycleCallbacks:
    # 初回登録時 処理
    prePersist:
      - fillTimestamps
