MiscBundle\Entity\TbSalesDetailVoucherYmA:
    type: entity
    table: tb_sales_detail_voucher_ym_a
    id:
        # 伝票番号:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
#    fields:
#        受注年月日:
#            type: date
#            nullable: false
#        受注年月:
#            type: string
#            nullable: false
#            length: 6
#            options:
#                fixed: false
#        受注年:
#            type: integer
#            nullable: true
#            options:
#                unsigned: false
#                default: '0'
#        受注月:
#            type: integer
#            nullable: true
#            options:
#                unsigned: false
#                default: '0'
#        店舗コード:
#            type: integer
#            nullable: false
#            options:
#                unsigned: false
#                default: '0'
#        ポイント数を含む総合計:
#            type: integer
#            nullable: false
#            options:
#                unsigned: false
#                default: '0'
#        明細数:
#            type: integer
#            nullable: false
#            options:
#                unsigned: false
#                default: '0'
#        総合計:
#            type: integer
#            nullable: true
#            options:
#                unsigned: false
#                default: '0'
#        商品計:
#            type: integer
#            nullable: true
#            options:
#                unsigned: false
#                default: '0'
#        税金:
#            type: integer
#            nullable: true
#            options:
#                unsigned: false
#                default: '0'
#        発送代:
#            type: integer
#            nullable: true
#            options:
#                unsigned: false
#                default: '0'
#        手数料:
#            type: integer
#            nullable: true
#            options:
#                unsigned: false
#                default: '0'
#        他費用:
#            type: integer
#            nullable: true
#            options:
#                unsigned: false
#                default: '0'
#        ポイント数:
#            type: integer
#            nullable: true
#            options:
#                unsigned: false
#                default: '0'
    lifecycleCallbacks: {  }
