MiscBundle\Entity\TbSalesDetailVoucherOrderYmRepeater:
    type: entity
    repositoryClass: MiscBundle\Entity\Repository\AnalyzedSalesDetailRepository
    table: tb_sales_detail_voucher_order_ym_repeater
    id:
        # 店舗コード:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
            id: true
        orderYM:
            type: string
            nullable: false
            length: 6
            column: 受注年月
            options:
                fixed: false
                default: ''
            id: true
#        購入回数:
#            type: integer
#            nullable: false
#            options:
#                unsigned: false
#            id: true
#    fields:
#        受注年:
#            type: integer
#            nullable: true
#            options:
#                unsigned: false
#                default: '0'
#        受注月:
#            type: integer
#            nullable: true
#            options:
#                unsigned: false
#                default: '0'
#        ポイント数を含む総合計:
#            type: float
#            nullable: true
#            precision: 10
#            scale: 0
#        明細数:
#            type: integer
#            nullable: false
#            options:
#                unsigned: false
#                default: '0'
#        伝票数:
#            type: integer
#            nullable: false
#            options:
#                unsigned: false
#                default: '0'
    lifecycleCallbacks: {  }
