MiscBundle\Entity\TbSalesDetailVoucherYmShop:
    type: entity
    repositoryClass: MiscBundle\Entity\Repository\AnalyzedSalesDetailRepository
    table: tb_sales_detail_voucher_ym_shop
    id:
        yyyymm:
            type: string
            nullable: false
            length: 6
            options:
                fixed: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        total:
            type: float
            nullable: false
            precision: 10
            scale: 0
            options:
                default: '0'
        shop01:
            type: float
            nullable: false
            precision: 10
            scale: 0
            options:
                default: '0'
        shop02:
            type: float
            nullable: false
            precision: 10
            scale: 0
            options:
                default: '0'
        shop03:
            type: float
            nullable: false
            precision: 10
            scale: 0
            options:
                default: '0'
        shop04:
            type: float
            nullable: false
            precision: 10
            scale: 0
            options:
                default: '0'
        shop05:
            type: float
            nullable: false
            precision: 10
            scale: 0
            options:
                default: '0'
        shop06:
            type: float
            nullable: false
            precision: 10
            scale: 0
            options:
                default: '0'
        shop07:
            type: float
            nullable: false
            precision: 10
            scale: 0
            options:
                default: '0'
        shop08:
            type: float
            nullable: false
            precision: 10
            scale: 0
            options:
                default: '0'
        shop09:
            type: float
            nullable: false
            precision: 10
            scale: 0
            options:
                default: '0'
        shop10:
            type: float
            nullable: false
            precision: 10
            scale: 0
            options:
                default: '0'
        shop11:
            type: float
            nullable: false
            precision: 10
            scale: 0
            options:
                default: '0'
        shop12:
            type: float
            nullable: false
            precision: 10
            scale: 0
            options:
                default: '0'
        shop13:
            type: float
            nullable: false
            precision: 10
            scale: 0
            options:
                default: '0'
        shop14:
            type: float
            nullable: false
            precision: 10
            scale: 0
            options:
                default: '0'
        shop15:
            type: float
            nullable: false
            precision: 10
            scale: 0
            options:
                default: '0'
        shop16:
            type: float
            nullable: false
            precision: 10
            scale: 0
            options:
                default: '0'
    lifecycleCallbacks: {  }
