MiscBundle\Entity\TbSetting:
    type: entity
    repositoryClass: MiscBundle\Entity\Repository\TbSettingRepository
    table: tb_setting
    id:
        settingKey:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: キー
            id: true
            column: setting_key
            # generator:
            #     strategy: IDENTITY
    fields:
        settingVal:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: 値
            column: setting_val
        settingDesc:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: 説明
            column: setting_desc
        nonDisplayFlag:
            type: boolean
            nullable: false
            comment: "各種設定画面非表示フラグ\n0:表示 1:非表示\n各種設定画面を利用せず、別に設定画面を提供する場合は1"
            default: '0'
            column: non_display_flag
        adminOnlyFlg:
            type: boolean
            nullable: false
            comment: "システム管理者限定フラグ\n0:無効 1:有効\nシステム管理者以外には非公開とする場合は1"
            default: '0'
            column: admin_only_flg
        updateAccountId:
            type: integer
            nullable: false
            unsigned: false
            comment: "更新者ID\nAccessやバッチの登録データの場合は0"
            default: '0'
            column: update_account_id
        updated:
            type: datetime
            nullable: false
            comment: "登録・更新日時\nWeb版各種設定に移行前に最後に更新されたデータはダミー値として2000-01-01を設定する（実際は2020/03以前のどこか）"
            default: CURRENT_TIMESTAMP

    lifecycleCallbacks:
        # 初回登録時 処理
        prePersist:
            - fillTimestamps
