MiscBundle\Entity\TbStockTransportDetail:
    type: entity
    table: tb_stock_transport_detail
    # indexes:
    id:
        transport_id:
            type: integer
            nullable: false
        ne_syohin_syohin_code:
            type: string
            length: 50
            nullable: false

    fields:
        amount:
            type: integer
            nullable: false
            options:
              default: 0
        picked:
            type: integer
            nullable: false
            options:
              default: 0
        shortage:
            type: integer
            nullable: false
            options:
              default: 0
            readOnly: true

        created:
            type: datetime
            nullable: false
        updated:
            type: datetime
            nullable: false

    lifecycleCallbacks:
        # 初回登録時 処理
        prePersist:
            - fillTimestamps
