MiscBundle\Entity\TbYahooAgentProduct:
  type: entity
  repositoryClass: MiscBundle\Entity\Repository\TbYahooAgentProductRepository
  table: tb_yahoo_agent_product
  # indexes:
  id:
    shop_code:
      type: string
      length: 20
      nullable: false
      default: ''
    daihyo_syohin_code:
      type: string
      length: 30
      nullable: false
      default: ''
  fields:
    product_code:
      type: string
      length: 30
      nullable: false
      default: ''
    product_name:
      type: string
      length: 255
      nullable: false
      default: ''
    genka_tanka:
      type: integer
      nullable: false
      default: 0
    baika_tanka:
      type: integer
      nullable: false
      default: 0
    registration_flg:
      type: integer
      nullable: false
      default: 0
    update_flg:
      type: integer
      nullable: false
      default: 0

    created:
      type: datetime
      nullable: false
    updated:
      type: datetime
      nullable: false

  lifecycleCallbacks:
    # 初回登録時 処理
    prePersist:
      - fillTimestamps

  manyToOne:
    product:
      targetEntity: TbMainproducts
      joinColumn:
        name: daihyo_syohin_code
        referencedColumnName: daihyo_syohin_code
      fetch: LAZY
