MiscBundle\Entity\TmpProductImages:
    type: entity
    repositoryClass: MiscBundle\Entity\Repository\TmpProductImagesRepository
    table: tmp_product_images
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: AUTO
    fields:
        image_key:
            type: string
            nullable: false
            length: 32
            options:
                fixed: false
        image_code:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
        daihyo_syohin_code:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
        image:
            type: string
            nullable: false
            default: ''
        delete_flg:
            type: integer
            nullable: false
            default: 0
        created:
            type: datetime
            nullable: false
        updated:
            type: datetime
            nullable: false

    # see http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/events.html#lifecycle-events
    lifecycleCallbacks:
        # 初回登録時 処理
        prePersist:
            - fillTimestamps
