<?php

namespace MiscBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TbSkuDescriptionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TbSkuDescriptionsRepository extends EntityRepository
{
}
