# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
  # twig 拡張 Text
  twig.extension.text:
    class: Twig_Extensions_Extension_Text
    tags:
       - { name: 'twig.extension' }

  misc.twig_extension:
    class: MiscBundle\Extend\Twig\Plusnao_Twig_Extension
    # public: false
    tags:
      - { name: twig.extension }