<?php

namespace MiscBundle\Entity\Repository;
use Doctrine\ORM\QueryBuilder;
use MiscBundle\Entity\ChouchouClairProductLog;
use MiscBundle\Util\DbCommonUtil;
use Plusnao\MainBundle\Form\Entity\ChouchouClairStockListDownloadCsvTypeEntity;
use Plusnao\MainBundle\Form\Entity\ChouchouClairStockListSearchTypeEntity;

/**
 * ChouchouClairProductLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChouchouClairProductLogRepository extends BaseRepository
{
  /**
   * ダウンロード履歴 最大在庫修正日時ログ 取得
   * @return ChouchouClairProductLog
   */
  public function getDownloadedMaxStockModifiedLog()
  {
    return $this->findOneBy(['operation' => 'CSVダウンロード'], ['last_stock_modified' => 'DESC']);
  }
}
