<?php

namespace MiscBundle\Entity\Repository;
use MiscBundle\Entity\ProductImagesAmazon;

/**
 * ProductImagesAmazonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductImagesAmazonRepository extends BaseRepository
{
  /**
   * 取得
   * @param $daihyoSyohinCode
   * @return ProductImagesAmazon
   * @throws \Doctrine\ORM\NonUniqueResultException
   */
  public function getMainImage($daihyoSyohinCode)
  {
    $qb = $this->createQueryBuilder('a');
    $qb->where('a.daihyo_syohin_code = :daihyoSyohinCode')->setParameter(':daihyoSyohinCode', $daihyoSyohinCode);
    $qb->andWhere('a.code = :code')->setParameter(':code', 'amazonMain');
    $ret = $qb->getQuery()->getOneOrNullResult();

    return $ret;
  }


  /**
   * Amazonメイン画像登録件数取得
   */
  public function getMainImageCount()
  {
    $dbMain = $this->getConnection('main');
    $sql = "SELECT COUNT(*) FROM product_images_amazon WHERE code = 'amazonMain'";
    return intval($dbMain->query($sql)->fetchColumn(0));
  }


}
