<?php

namespace MiscBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Tb1688VendorProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Tb1688VendorProductRepository extends BaseRepository
{
}
