<?php

namespace MiscBundle\Entity\Repository;

/**
 * Tb1688CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Tb1688CompanyRepository extends BaseRepository
{
}
