<?php

namespace MiscBundle\Entity\Repository;


/**
 * Tb1688ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Tb1688ProductRepository extends BaseRepository
{
  const OFFER_STATUS_ONLINE = 'online';
  const OFFER_STATUS_OUTDATED = 'outdated';
  const OFFER_STATUS_MEMBER_DELETED = 'member deleted';
  const OFFER_STATUS_FAIL_AUDITED = 'failAudited';
  const OFFER_STATUS_DELETED = 'deleted';

  // 独自ステータス APIで取得不可
  const OFFER_STATUS_MISSING = '__MISSING__';

}
