<?php

namespace MiscBundle\Entity\Repository;
use MiscBundle\Entity\TbDeliveryPickingBlock;
use MiscBundle\Entity\TbWarehouse;

/**
 * TbDeliveryPickingBlockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TbDeliveryPickingBlockRepository extends BaseRepository
{
  /**
   * ブロック一覧取得
   * @param TbWarehouse $warehouse
   * @return array
   */
  public function getBlocks($warehouse)
  {
    $result = [];
    /** @var BaseRepository $repoDetail */
    $repoDetail = $this->getContainer()->get('doctrine')->getRepository('MiscBundle:TbDeliveryPickingBlockDetail');

    /** @var TbDeliveryPickingBlock[] $blocks */
    $blocks = $this->findBy([ 'warehouse_id' => $warehouse->getId() ], [ 'display_order' => 'DESC' ]);
    foreach($blocks as $block) {
      $data = [];
      $data['block'] = $block;
      $condition = [
          'warehouse_id' => $block->getWarehouseId()
        , 'block_code' => $block->getBlockCode()
      ];
      $data['details'] = $repoDetail->findBy($condition, [ 'pattern' => 'ASC' ]);

      $result[] = $data;
    }

    return $result;
  }
}
