<?php

namespace MiscBundle\Entity\Repository;

/**
 * TbDeleteExcludedProductsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TbDeleteExcludedProductsRepository extends \Doctrine\ORM\EntityRepository
{
}
