<?php

namespace MiscBundle\Entity\Repository;
use MiscBundle\Entity\TbDiscountSetting;

/**
 * TbDiscountSettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TbDiscountSettingRepository extends BaseRepository
{
  const CURRENT_SETTING_ID = 1;

    const CURRENT_SETTING_ID_COPY = 2;

  /**
   * 設定取得
   */
  public function getCurrentSetting()
  {
    $result = $this->find(self::CURRENT_SETTING_ID);
    if (!$result) {
      $class = $this->getEntityName();

      /** @var TbDiscountSetting $result */
      $result = new $class();
      $result->setId(self::CURRENT_SETTING_ID)
             ->setDiscountExcludedDays(10)
             ->setSalesTermDays(365)
             ->setSalesSamplingDays(90)
             ->setSellOutDays(90)
             ->setAllowedSellOutOverDays(90)
             ->setMaxDiscountRate(1);

      $em = $this->getEntityManager();
      $em->persist($result);
      $em->flush();
    }

    return $result;
  }

  /**
   * 新値下げ機能　設定値取得（なければ初期化）
   * 旧機能に存在した値下げ猶予日数とオーバー許容日数は、不要になるが not nullのため0を設定
   */
  public function getCurrentSettingCopy()
  {
    $result = $this->find(self::CURRENT_SETTING_ID_COPY);
    if (!$result) {
      $class = $this->getEntityName();

      /** @var TbDiscountSetting $result */
      $result = new $class();
      $result->setId(self::CURRENT_SETTING_ID_COPY)
             ->setDiscountExcludedDays(0)
             ->setSalesTermDays(365)
             ->setSalesSamplingDays(90)
             ->setSellOutDays(90) // 画面表示時は30で割る、設定する場合は30を掛ける
             ->setAllowedSellOutOverDays(0)
             ->setMaxDiscountRate(1);

      $em = $this->getEntityManager();
      $em->persist($result);
      $em->flush();
    }
    return $result;
  }
}
