<?php

namespace MiscBundle\Entity\Repository;

use MiscBundle\Entity\TbIndividualorderComment;
use Doctrine\ORM\EntityRepository;

/**
 * TbIndividualorderCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TbIndividualorderCommentRepository extends BaseRepository
{
  /**
   * @param $voucherNumber
   * @param $agentCode
   * @param $comment
   * @param $accountId
   */
  public function updateComment($voucherNumber, $agentCode, $comment, $accountId)
  {
    $em = $this->getEntityManager();

    if ($this->existRecord($voucherNumber, $agentCode) === true) {
      $record = $this->findOneBy(['order_voucher_number' => $voucherNumber, 'agent_id' => $agentCode]);
      $record->setNote($comment);
    } else {
      $record = new TbIndividualorderComment();
      $record->setOrderVoucherNumber($voucherNumber);
      $record->setAgentId($agentCode);

      $record->setNote($comment);
      $record->setUpdateAccountId($accountId);
      $record->setUpdated(new \DateTime());
    }

    $em->persist($record);
    $em->flush();
  }

  /**
   * レコードが存在するか
   * @param $voucherNumber
   * @param $agentCode
   * @return bool
   */
  private function existRecord($voucherNumber, $agentCode)
  {
    $record = $this->findOneBy(['order_voucher_number' => $voucherNumber, 'agent_id' => $agentCode]);
    return $record !== null;
  }

}
