<?php

namespace MiscBundle\Entity\Repository;

use MiscBundle\Entity\TbPickingScore;

/**
 * TbPickingScoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TbPickingScoreRepository extends BaseRepository
{
  /**
   * ピッキングリストをカラムで取得
   * @return array
   */
  public function fetchPickingScoreList()
  {
    $qb = $this->createQueryBuilder('ps');
    return $qb->select()->getQuery()->getArrayResult();
  }

  /**
   * テーブルを$listの内容で上書きする
   * @param array<TbPickingScore> $list
   */
  public function overwrite($list)
  {
    $em = $this->getEntityManager();
    $em->beginTransaction();
    try {
      $em->createQueryBuilder()->delete('MiscBundle:TbPickingScore', 'ps')->getQuery()->getResult();

      foreach ($list as $scores) {
        $em->persist($scores);
      }
      $em->flush();
      $em->commit();
    } catch (\Exception $e) {
      try {
        $em->rollback();
      } catch (\Exception $e2) {
        $logger = $this->getLogger();
        $logger->info('ピッキングスコア更新時のrollbackでエラー: '. $e2->getMessage() . $e2->getTraceAsString());
      }
      throw $e;
    }
  }
}
