<?php

namespace MiscBundle\Entity\Repository;
use Doctrine\ORM\Query\ResultSetMapping;
use Doctrine\ORM\Query\ResultSetMappingBuilder;
use MiscBundle\Entity\TbProductchoiceitems;
use MiscBundle\Util\BatchLogger;

/**
 * TbProductchoiceitemsFormerSizeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TbProductchoiceitemsFormerSizeRepository extends BaseRepository
{

  /**
   * tb_productchoiceimtesの現在のデータと、
   * 前の実行時に取得した、tb_productchoiceitems_former_size テーブルにに格納されているデータを比較して、
   * 差分があるデータの ChangedFlg=1とする。
   */
  public function updateChangedData() {
    $this->updateChangedFlg();
    $this->addDiffItems();
  }

  /**
   * 現在値と過去値を比較して、差分があるデータの ChangedFlg=1とする。
   */
  private function updateChangedFlg() {
    $dbMain = $this->getConnection('main');
    $sql = <<<EOD
      UPDATE tb_productchoiceitems_former_size fs
      INNER JOIN tb_productchoiceitems pci ON fs.ne_syohin_syohin_code = pci.ne_syohin_syohin_code
      SET fs.changed_flg = 1
      WHERE pci.weight <> fs.weight
        OR pci.depth <> fs.depth
        OR pci.width <> fs.width
        OR pci.height <> fs.height
EOD;
    $stmt = $dbMain->prepare($sql);
    $stmt->execute();
  }

  /**
   * 実テーブル（TbProductchoiceitems）にのみデータがあり、差分保持テーブル（TbProductchoiceitemsFormerSize）に
   * データがないレコードを、ChangeFlg=1として追加登録する。
   * 以前はデータ自体がなかったということで、サイズ・重量は全てnullとなる。
   */
  private function addDiffItems() {
    $dbMain = $this->getConnection('main');
    $sql = <<<EOD
      INSERT INTO tb_productchoiceitems_former_size
      SELECT pci.ne_syohin_syohin_code, null as weight, null as depth, null as width, null as height, 1 as changedFlg
      FROM tb_productchoiceitems pci
      LEFT JOIN tb_productchoiceitems_former_size fs ON pci.ne_syohin_syohin_code = fs.ne_syohin_syohin_code
      WHERE fs.ne_syohin_syohin_code IS NULL
EOD;
    $stmt = $dbMain->prepare($sql);
    $stmt->execute();
  }

  /**
   * 登録中の全データを削除し、最新データで更新する。
   */
  public function refleshAll() {
    $dbMain = $this->getConnection('main');

    // 全削除
    $dbMain->query("TRUNCATE tb_productchoiceitems_former_size");

    $sql = <<<EOD
      INSERT
      INTO tb_productchoiceitems_former_size
      SELECT
        pci.ne_syohin_syohin_code
        , pci.weight as weight
        , pci.depth as depth
        , pci.width as width
        , pci.height as height
        , 0 as changedFlg
      FROM
        tb_productchoiceitems pci
EOD;
    $stmt = $dbMain->prepare($sql);
    $stmt->execute();
  }

}