<?php

namespace MiscBundle\Entity\Repository;

use Doctrine\DBAL\DBALException;

/**
 * TbProductchoiceitemsColor
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TbProductchoiceitemsColorRepository extends BaseRepository
{
  /**
   * SKU別カラー種別の更新
   * @throws DBALException
   */
  public function updateSkuColor()
  {
    // 2テーブルの差を解消
    $this->solveDifference();
    // SKUごとにカラーが異なるものを未設定に更新
    $this->updateDifferentColorsToUnset();
    // 未設定で複数SKUが存在すれば1件だけ残して削除
    $this->deleteDuplicatedUnsetSku();
    // それぞれのYahooSpecValueIdを設定
    $this->setUpYahooSpecValueId();
  }

  /**
   * tb_productchoiceitems と tb_productchoiceitems_color の差を解消する
   * 商品やSKUの追加・削除による差分解消
   * @throws DBALException
   */
  private function solveDifference()
  {
    $dbMain = $this->getConnection('main');

    // tb_productchoiceitems_color にあり tb_productchoiceitems にないレコードを削除
    $sql = <<<EOD
        DELETE color 
        FROM tb_productchoiceitems_color color
        LEFT JOIN tb_productchoiceitems choice 
          ON color.ne_syohin_syohin_code = choice.ne_syohin_syohin_code 
        WHERE choice.ne_syohin_syohin_code IS NULL;
EOD;
    $dbMain->query($sql);

    // tb_productchoiceitems にあり tb_productchoiceitems_color にないレコードを追加
    $sql = <<<EOD
      INSERT INTO tb_productchoiceitems_color
        (ne_syohin_syohin_code, yahoo_spec_value_id, color_name, configured_flg)
      SELECT 
        choice.ne_syohin_syohin_code,
        NULL AS yahoo_spec_value_id,
        CASE main.`カラー軸` 
          WHEN 'row' THEN choice.rowname
          WHEN 'col' THEN choice.colname
          ELSE ''
        END AS color_name,
        0 AS configured_flg
      FROM tb_productchoiceitems choice 
      INNER JOIN tb_mainproducts main 
        ON choice.daihyo_syohin_code = main.daihyo_syohin_code
      LEFT JOIN tb_productchoiceitems_color color 
        ON choice.ne_syohin_syohin_code = color.ne_syohin_syohin_code
      WHERE color.ne_syohin_syohin_code IS NULL;
EOD;
    $dbMain->query($sql);
  }

  /**
   * tb_productchoiceitemsのカラー名と一致しないレコードを未設定に更新する
   * @throws DBALException
   */
  private function updateDifferentColorsToUnset()
  {
    $dbMain = $this->getConnection('main');

    $sql = <<<EOD
      UPDATE tb_productchoiceitems_color color
      INNER JOIN tb_productchoiceitems choice 
        ON color.ne_syohin_syohin_code = choice.ne_syohin_syohin_code
      INNER JOIN tb_mainproducts main 
        ON choice.daihyo_syohin_code = main.daihyo_syohin_code
      SET 
        color.yahoo_spec_value_id = NULL,
        color.color_name = CASE main.`カラー軸` 
          WHEN 'row' THEN choice.rowname
          WHEN 'col' THEN choice.colname
          ELSE ''
        END,   
        color.configured_flg = 0
      WHERE
       CASE main.`カラー軸` 
          WHEN 'row' THEN choice.rowname
          WHEN 'col' THEN choice.colname
          ELSE ''
        END != color.color_name;
EOD;
    $dbMain->query($sql);
  }

  /**
   * 1SKUごとに設定済みフラグが0のレコードが1件だけ残し、他は削除
   * 仕様として同一SKUでconfigured_flgが異なることはない
   * @throws DBALException
   */
  private function deleteDuplicatedUnsetSku()
  {
    $dbMain = $this->getConnection('main');

    // 同一SKUで集約しidを一つに絞る
    // そのid以外の同一SKUはidで結合できずT.idはNULLになる
    $sql = <<<EOD
      DELETE del_color FROM tb_productchoiceitems_color del_color
      LEFT JOIN (
        SELECT color.id 
        FROM tb_productchoiceitems_color color
        WHERE color.configured_flg = 0
        GROUP BY color.ne_syohin_syohin_code
        ) T 
        ON del_color.id = T.id
      WHERE T.id IS NULL
        AND del_color.configured_flg = 0 
EOD;
    $dbMain->query($sql);
  }

  /**
   * 未設定のSKUにyahoo_spec_value_idを設定する
   */
  private function setUpYahooSpecValueId()
  {
    $dbMain = $this->getConnection('main');

    // yahoo_spec_value_idを設定
    $sql = <<<EOD
      UPDATE tb_productchoiceitems_color color
      INNER JOIN tb_color_mapping map 
        ON color.color_name = map.sku_color_name
      INNER JOIN tb_color_type color_type 
        ON map.color_type_id = color_type.id
      SET color.yahoo_spec_value_id = color_type.yahoo_spec_value_id
      WHERE color.configured_flg = 0
EOD;
    $dbMain->query($sql);

    // すべて設定済みとする
    $sql = <<<EOD
      UPDATE tb_productchoiceitems_color color
      SET color.configured_flg = 1;
EOD;
    $dbMain->query($sql);
  }
}
