<?php

namespace MiscBundle\Entity\Repository;

/**
 * TbRakutenKeywordRankingLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TbRakutenKeywordRankingLogRepository extends \Doctrine\ORM\EntityRepository
{
}
