<?php

namespace MiscBundle\Entity\Repository;

/**
 * TbRealShopInformationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TbRealShopInformationRepository extends BaseRepository
{
}
