<?php

namespace MiscBundle\Entity\Repository;

use Doctrine\ORM\Query\ResultSetMapping;
use Symfony\Component\Form\Exception\RuntimeException;
use Symfony\Component\Form\Form;

/**
 * TbVendorCostRateLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TbSalesDetailBuycountRepository extends BaseRepository
{
}
