<?php

namespace MiscBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TbSdInformationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TbSdInformationRepository extends EntityRepository
{
}
