<?php
namespace MiscBundle\Entity\Repository;
use MiscBundle\Entity\TbShoppingMall;

/**
 * TbShoppingMallRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TbShoppingMallRepository extends BaseRepository
{
  public function getMallListByIds($ids = [])
  {
    $mallList = [];

    $qb = $this->createQueryBuilder('m');
    if ($ids) {
      $qb->andWhere($qb->expr()->in('m.mallId', $ids));
    }

    $qb->addOrderBy('m.mallId', 'asc');

    /** @var TbShoppingMall[] $malls */
    $malls = $qb->getQuery()->getResult();
    foreach($malls as $mall) {
      $mallList[$mall->getMallId()] = $mall;
    }

    return $mallList;
  }

  /**
   * 店舗情報取得 (全店舗全フィールド)
   */
  public function getAllMalls()
  {
    $list = [];

    $qb = $this->createQueryBuilder('m');
    $qb->orderBy('m.mallSort', 'ASC');
    /** @var TbWarehouse[] $result */
    $malls = $qb->getQuery()->getResult();

    foreach($malls as $mall) {
      $list[] = $mall->toScalarArray();
    }

    return $list;
  }

}
