<?php

namespace MiscBundle\Entity\Repository;
use MiscBundle\Entity\TbSkuDescriptions;

/**
 * TbSkuDescriptionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TbSkuDescriptionsRepository extends BaseRepository
{

  /**
   * description_en、description_cnが同一のデータ件数取得
   */
  public function getSameDescriptionCount($id, $descriptionEn, $descriptionCn)
  {
    $logger = $this->getContainer()->get('misc.util.batch_logger');
    $db = $this->getConnection('main');
    $params = [];
    $sql = <<<EOD
      SELECT
        COUNT(d.id) AS cnt
      FROM tb_sku_descriptions d
      WHERE d.description_en = :descriptionEn
        AND d.description_cn = :descriptionCn
        AND d.description_delete_flg = 0
EOD;
    $params[':descriptionEn'] = $descriptionEn;
    $params[':descriptionCn'] = $descriptionCn;
    if (isset($id) && strlen($id)) {
      $sql = $sql.' AND d.id <> :id';
      $params[':id'] = $id;
    }
    $stmt = $db->prepare($sql);
    foreach($params as $k => $v) {
      $stmt->bindValue($k, $v, \PDO::PARAM_STR);
    }
    $stmt->execute();
    
    $result = intval($stmt->fetchColumn(0));
    return $result;
  }

  /**
   * description_enが同一のデータ件数取得
   */
  public function getEnSameDescriptionCount($id, $descriptionEn)
  {
    $db = $this->getConnection('main');
    $params = [];
    $sql = <<<EOD
      SELECT
        COUNT(d.id) AS cnt
      FROM tb_sku_descriptions d
      WHERE d.description_en = :descriptionEn
        AND d.description_delete_flg = 0
EOD;
    $params[':descriptionEn'] = $descriptionEn;
    if (isset($id) && strlen($id)) {
      $sql = $sql.' AND d.id <> :id';
      $params[':id'] = $id;
    }
    $stmt = $db->prepare($sql);
    foreach($params as $k => $v) {
      $stmt->bindValue($k, $v, \PDO::PARAM_STR);
    }
    $stmt->execute();
    
    $result = intval($stmt->fetchColumn(0));
    return $result;
  }

  /**
   * description_cnが同一のデータ件数取得
   */
  public function getCnSameDescriptionCount($id, $descriptionCn)
  {
    $db = $this->getConnection('main');
    $params = [];
    $sql = <<<EOD
      SELECT
        COUNT(d.id) AS cnt
      FROM tb_sku_descriptions d
      WHERE d.description_cn = :descriptionCn
        AND d.description_delete_flg = 0
EOD;
    $params[':descriptionCn'] = $descriptionCn;
    if (isset($id) && strlen($id)) {
      $sql = $sql.' AND d.id <> :id';
      $params[':id'] = $id;
    }
    $stmt = $db->prepare($sql);
    foreach($params as $k => $v) {
      $stmt->bindValue($k, $v, \PDO::PARAM_STR);
    }
    $stmt->execute();
    
    $result = intval($stmt->fetchColumn(0));
    return $result;
  }

}
