<?php

namespace MiscBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use MiscBundle\Entity\TbVendormasterdata;
use MiscBundle\Util\BatchLogger;

/**
 * TbVendormasterdataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TbVendormasterdataRepository extends BaseRepository
{
  public function fetchActiveSireData()
  {
    $qb = $this->createQueryBuilder('d');
    $qb->where('d.status = :active')->setParameter(':active', 0);
    $sireData = $qb->getQuery()->getResult();

    $vendorData = [];
    foreach ($sireData as $sireDatum){
      $vendorData[$sireDatum->getSireCode()] = $sireDatum->getSireName();
    }

    return $vendorData;
  }
}
