<?php

namespace MiscBundle\Entity\Repository;
use MiscBundle\Entity\TbYahooApiAuth;

/**
 * TbYahooApiAuthRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TbYahooApiAuthRepository extends BaseRepository
{
  /**
   * 最新のAPI認証情報を取得する
   * -> access_token の expiration で判定
   * @return TbYahooApiAuth
   */
  public function findLatestAuth()
  {
    $result = null;

    $qb = $this->createQueryBuilder('auth');
    $qb->where("auth.access_token <> ''")
       ->andWhere("auth.refresh_token <> ''")
       ->orderBy("auth.expiration", 'DESC')
       ->setMaxResults(1);

    $query = $qb->getQuery();
    $list = $query->getResult();
    if ($list) {
      $result = array_shift($list);
    }

    return $result;
  }

}
